### ISSUE TITLE
Check timestamps on getRawTx return values, find an appropriate one and add a security check on verifyPaymentInfo

### ISSUE THREAD

**Issue by jamiemadrox779** [DistributedCollective/fastBTC-confirmation-node#27]
Blocktime, time or timereceived should be good candidates.
If the timestamp is older than 1h the node should not confirm the tx.

**Comment by Bitcoinera** [comment]
First I need to fix #26 , ofc

EDIT: Sorry, I meant fixing the fact that the transaction is returning from DB is null
